# Generated by Django 5.2 on 2025-04-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
