# Generated by Django 5.1.7 on 2025-03-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('email', models.CharField(max_length=15, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updtedat', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
