# Generated by Django 5.1.7 on 2025-03-20 06:36
from django.contrib.auth.models import Group, Permission
from django.db import migrations, models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType




class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_customuser_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
