# Generated by Django 5.1.7 on 2025-03-20 07:14

from django.db import migrations, models
# Generated by Django 5.1.7 on 2025-03-20 06:36
from django.contrib.auth.models import Group, Permission
from django.db import migrations, models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType

def create_groups_permissions(apps,schema_editor):
    User = get_user_model()
    user_content_type = ContentType.objects.get_for_model(User)

    anonymous_group, _ = Group.objects.get_or_create(name="anonymous")
    authenticated_group, _ = Group.objects.get_or_create(name="authenticated_user")
    moderator_group, _ = Group.objects.get_or_create(name="moderator")
    admin_group, _ = Group.objects.get_or_create(name="admin")
    anonymous_group.permissions.clear()


def reverse(apps,schema_editor):
    Group.objects.filter(name__in=['anonymus','authenticated_user','moderator','admin']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=27, unique=True),
        ),
        migrations.RunPython(create_groups_permissions,reverse)
    ]
