# Generated by Django 5.1.7 on 2025-03-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Fetch or create groups
    user_group, _ = Group.objects.get_or_create(name="user")
    moderator_group, _ = Group.objects.get_or_create(name="moderator")
    admin_group, _ = Group.objects.get_or_create(name="admin")

    # Get permissions
    content_type = apps.get_model("contenttypes", "ContentType").objects.get(app_label="forums", model="profile")
    
    user_permissions = [
        "add_profile", "change_profile", "delete_profile",
        "add_forum", "change_forum", "add_comment", "add_like"
    ]
    
    moderator_permissions = user_permissions + [
        "change_forum", "delete_forum", "delete_comment", "delete_like"
    ]

    admin_permissions = moderator_permissions + [
        "add_user", "change_user", "delete_user", "add_group", "change_group"
    ]

    


def remove_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["user", "moderator", "admin"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.RunPython(assign_permissions, remove_permissions)
    ]
