# Generated by Django 5.1.7 on 2025-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='age',
        ),
        migrations.AddField(
            model_name='posts',
            name='Content',
            field=models.TextField(null=True),
        ),
    ]
