# Generated by Django 5.2 on 2025-04-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.IntegerField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('software_v', models.CharField(max_length=10)),
            ],
        ),
    ]
