# Generated by Django 5.2 on 2025-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='model',
            field=models.IntegerField(),
        ),
    ]
